services:
  - type: web
    name: permission-militaire
    plan: free
    region: frankfurt
    runtime: docker
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db-permission
          property: connectionString

databases:
  - name: db-permission
    region: frankfurt
