parameters:
    # Paramètres personnalisés si besoin (exemple : nom de l'app)
    app.name: 'Gestion Permissions Militaires'

services:
    # ⚙️ Configuration par défaut
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique (commandes, events…)
        bind:
            $appName: '%app.name%' # Injection automatique d’un paramètre commun

    # ⛓️ Tous les services dans src/ sont enregistrés automatiquement
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Exemple de service personnalisé si tu crées un login success handler
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'
            $security: '@security.helper'
